//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_999A5F_WDQWeiXinEntities : DbContext
    {
        public DB_999A5F_WDQWeiXinEntities()
            : base("name=DB_999A5F_WDQWeiXinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EventMsg> EventMsg { get; set; }
        public DbSet<ImageMsg> ImageMsg { get; set; }
        public DbSet<LinkMsg> LinkMsg { get; set; }
        public DbSet<LocationMsg> LocationMsg { get; set; }
        public DbSet<TextMsg> TextMsg { get; set; }
        public DbSet<VideoMsg> VideoMsg { get; set; }
        public DbSet<VoiceMsg> VoiceMsg { get; set; }
    }
}
